#!/usr/bin/env bash
#script with while loop and if
num=1
while [ $num -le 10 ]
do 
   if [ $num -eq 9 ]
   then
       echo "Best School"
       echo "Hi"
   else
        echo "Best School"
   fi
   ((num++))
done
