#!/usr/bin/env bash
# script about time formating
hours=0
while [ $hours -le 12 ]
do
  echo "Hours: $hours"
  minutes=1
  while [ $minutes -le 59 ]
  do
    echo "$minutes"
    ((minutes++))
  done
  ((hours++))
done
